INSERT INTO USER_RATING (ID, NAME, MOVIE_RATING, MOVIE_ID) VALUES (1, 'Hasham Rasheed', 9, 1);
INSERT INTO USER_RATING (ID, NAME, MOVIE_RATING, MOVIE_ID) VALUES (2, 'Zaid Khan', 8, 2);
INSERT INTO USER_RATING (ID, NAME, MOVIE_RATING, MOVIE_ID) VALUES (3, 'Ali Raza', 7, 3);